include:
  - zabbix-base.yml

services:
  zabbix-agent:
    image: ${ZABBIX_AGENT_IMAGE_TAG}
    container_name: zabbix-agent
    environment:
      ZBX_HOSTNAME: Zabbix server
      ZBX_SERVER_HOST: zabbix-server
    restart: unless-stopped
    depends_on:
      - postgres
      - zabbix-server
    volumes:
      - type: bind
        source: /dev
        target: /host/dev
      - type: bind
        source: /proc
        target: /host/proc
      - type: bind
        source: /
        target: /host/rootfs
