include:
  - zabbix-base.yml

services:
  zabbix-agent:
    image: ${ZABBIX_AGENT_IMAGE_TAG}
    container_name: zabbix-agent
    environment:
      ZBX_HOSTNAME: Zabbix server
      ZBX_SERVER_HOST: zabbix-server
    restart: unless-stopped
    depends_on:
      - postgres
      - zabbix-server
